# Generated by Django 5.0.4 on 2024-05-20 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('item_account', '0001_initial'),
        ('order', '0001_initial'),
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounts',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to='item_account.item_account'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='debit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_account', to='item_account.item_account'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='order_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.order'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='purchase_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='purchase.purchase'),
        ),
    ]
