# Generated by Django 5.0.4 on 2024-05-21 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accounts_options_alter_accounts_order_info_and_more'),
        ('order', '0002_initial'),
        ('purchase', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='order_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.order'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='purchase_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='purchase.purchase'),
        ),
    ]
